export const BANGALORE_WARDS = [
  "A. Narayanapura (Ward 94)",
  "AECS Layout (Ward 102)",
  "Adugodi (Ward 176)",
  "Agaram (Ward 172)",
  "Amrutahalli (Ward 8)",
  "Anjanapura (Ward 208)",
  "Aramane Nagara (Ward 56)",
  "Attiguppe (Ward 150)",
  "Atturu (Ward 3)",
  "Avalahalli (Ward 152)",
  "Azad Nagar (Ward 159)",
  "BTM Layout (Ward 181)",
  "Bagalakunte (Ward 18)",
  "Banasavadi (Ward 82)",
  "Banashankari Temple ward (Ward 191)",
  "Bande Mutt (Ward 31)",
  "Basavanagudi (Ward 198)",
  "Basavanapura (Ward 92)",
  "Basaveshwara Nagar (Ward 133)",
  "Begur (Ward 211)",
  "Belatur (Ward 98)",
  "Bellanduru (Ward 107)",
  "Benniganahalli (Ward 109)",
  "Bharathi Nagar (Ward 120)",
  "Bilekhalli (Ward 215)",
  "Binnipete (Ward 126)",
  "Bommanahalli (Ward 218)",
  "Byadarahalli (Ward 27)",
  "Byatarayanapura (Ward 10)",
  "Byrasandra (Ward 182)",
  "C V Raman Nagar (Ward 110)",
  "Chalavadipalya (Ward 156)",
  "Challakere (Ward 86)",
  "Chamrajapet (Ward 158)",
  "Chamundi Nagara (Ward 66)",
  "Chandralayout (Ward 142)",
  "Chickpete (Ward 128)",
  "Chikkalsandra (Ward 194)",
  "Chikkasandra (Ward 17)",
  "Chokkasandra (Ward 21)",
  "Chowdeshwari Nagar (Ward 40)",
  "Chowdeswari Ward (Ward 2)",
  "Cottonpete (Ward 127)",
  "Cox Town (Ward 108)",
  "Dattatreya Temple (Ward 122)",
  "Dayananda Nagar (Ward 129)",
  "Deepanjali Nagar (Ward 151)",
  "Devagiri Temple Ward (Ward 190)",
  "Devara Jeevanahalli (Ward 72)",
  "Devaraj Urs Nagar (Ward 155)",
  "Devasandra (Ward 93)",
  "Dharmaraya Swamy Temple (Ward 160)",
  "Dodda Bidarakallu (Ward 26)",
  "Dodda Bommasandra (Ward 12)",
  "Dodda Nekkundi (Ward 101)",
  "Domlur (Ward 171)",
  "Dr. Puneet Rajkumar (Ward 50)",
  "Dr. Raj Kumar Ward (Ward 135)",
  "Ejipura (Ward 173)",
  "Gali Anjaneya Temple Ward (Ward 149)",
  "Gandhinagar (Ward 123)",
  "Ganesh Mandir ward (Ward 189)",
  "Ganga Nagar (Ward 67)",
  "Garudachar Palya (Ward 100)",
  "Gayithri Nagar (Ward 60)",
  "Gharebhavipalya (Ward 220)",
  "Girinagar (Ward 200)",
  "Gottigere (Ward 209)",
  "Govindaraja Nagar (Ward 136)",
  "Gurappanapalya (Ward 183)",
  "HAL Airport (Ward 96)",
  "HBR Layout (Ward 78)",
  "HSR Layout (Ward 221)",
  "Hampi Nagar (Ward 147)",
  "Hanumanth Nagar (Ward 196)",
  "Hebbal Kempapura (Ward 9)",
  "Hebbala (Ward 63)",
  "Hegganahalli (Ward 24)",
  "Hemmigepura (Ward 33)",
  "Hennur (Ward 76)",
  "Herohalli (Ward 28)",
  "Hombegowda Nagar (Ward 164)",
  "Hongasandra (Ward 219)",
  "Horamavu (Ward 87)",
  "Hosa Road (Ward 224)",
  "Hosahalli (Ward 146)",
  "Hosakerehalli (Ward 195)",
  "Hoysala Nagar (Ward 113)",
  "Hudi (Ward 99)",
  "Hulimavu (Ward 216)",
  "Ibluru (Ward 222)",
  "J P Nagar (Ward 185)",
  "JP Park (Ward 34)",
  "Jakkasandra (Ward 175)",
  "Jakkuru (Ward 6)",
  "Jalahalli (Ward 36)",
  "Jaraganahalli (Ward 213)",
  "Jayachamarajendra  Nagar (Ward 68)",
  "Jayanagar East (Ward 184)",
  "Jeevanbhima Nagar (Ward 114)",
  "Jnana Bharathi ward (Ward 44)",
  "Jogupalya (Ward 170)",
  "K R Market (Ward 157)",
  "K R Puram (Ward 91)",
  "KSFC Layout (Ward 83)",
  "Kacharkanahalli (Ward 80)",
  "Kadu Malleshwar Ward (Ward 58)",
  "Kadugodi (Ward 97)",
  "Kadugondanahalli (Ward 79)",
  "Kaggadasanapura (Ward 111)",
  "Kalena Agrahara (Ward 210)",
  "Kalkere (Ward 88)",
  "Kamakshipalya (Ward 134)",
  "Kammagondanahalli (Ward 15)",
  "Kammanahalli (Ward 81)",
  "Katriguppe (Ward 201)",
  "Kaval Bairasandra (Ward 69)",
  "Kaveripura (Ward 138)",
  "Kempapura Agrahara (Ward 144)",
  "Kempegowda Ward (Ward 1)",
  "Kengeri (Ward 32)",
  "Kodichikkanahalli (Ward 217)",
  "Kodigehalli (Ward 11)",
  "Kogilu (Ward 5)",
  "Konanakunte (Ward 206)",
  "Konena Agrahara (Ward 115)",
  "Koramangala (Ward 174)",
  "Kottegepalya (Ward 41)",
  "Kudlu (Ward 225)",
  "Kumaraswamy Layout (Ward 192)",
  "Kushal Nagar (Ward 70)",
  "Kuvempu Nagar (Ward 14)",
  "Laggere (Ward 39)",
  "Lakkasandra (Ward 177)",
  "Laxmidevi Nagar (Ward 38)",
  "Lingarajapura (Ward 84)",
  "Madivala (Ward 179)",
  "Mahalakshimpuram (Ward 48)",
  "Malathalli (Ward 43)",
  "Mallasandra (Ward 16)",
  "Malleswaram (Ward 55)",
  "Mangammanapalya (Ward 223)",
  "Manorayanapalya (Ward 65)",
  "Marappana Palya (Ward 46)",
  "Marathahalli (Ward 106)",
  "Marenahalli (Ward 137)",
  "Maruthi Mandir ward (Ward 140)",
  "Maruthi Seva Nagar (Ward 85)",
  "Mattikere (Ward 54)",
  "Mudalapalya (Ward 139)",
  "Munekollal (Ward 105)",
  "Muneshwara Nagar (Ward 71)",
  "Nagadevanahalli (Ward 30)",
  "Naganathapura (Ward 212)",
  "Nagapura (Ward 49)",
  "Nagarabhavi (Ward 141)",
  "Nagavara (Ward 77)",
  "Nalagadarenahalli (Ward 20)",
  "Nandini Layout (Ward 47)",
  "Nayandahalli (Ward 143)",
  "New Guddadahalli (Ward 148)",
  "New Tippasandara (Ward 112)",
  "Nilasandra (Ward 168)",
  "Okalipuram (Ward 125)",
  "Padarayanapura (Ward 153)",
  "Padmanabha Nagar (Ward 193)",
  "Peenya (Ward 37)",
  "Peenya Industrial Area (Ward 22)",
  "Prakash Nagar (Ward 130)",
  "Pulikeshinagar (Ward 75)",
  "Puttenahalli (Ward 214)",
  "RBI layout (Ward 207)",
  "Radhakrishna Temple Ward (Ward 61)",
  "Rajagopal Nagar (Ward 23)",
  "Rajamahal Guttahalli (Ward 57)",
  "Rajarajeshwari Nagar (Ward 45)",
  "Ramamurthy Nagar (Ward 90)",
  "Ramaswamypalya (Ward 116)",
  "Rayapuram (Ward 154)",
  "S K Garden (Ward 73)",
  "S.R.Nagar (Ward 118)",
  "Sagayarapuram (Ward 74)",
  "Sanjaya Nagar (Ward 62)",
  "Sarakki (Ward 187)",
  "Shakambari Nagar (Ward 186)",
  "Shakthi Ganapathi Nagar (Ward 52)",
  "Shankar Matt (Ward 51)",
  "Shantala Nagar (Ward 167)",
  "Shanthi Nagar (Ward 166)",
  "Shivaji Nagar (Ward 119)",
  "Shivanagara (Ward 132)",
  "Silver Jublee Park (Ward 161)",
  "Someshwara Nagar (Ward 165)",
  "Someswara Temple Ward (Ward 180)",
  "Srigandhadakaval (Ward 42)",
  "Srinagar (Ward 197)",
  "Sriramamandir (Ward 131)",
  "Subhash Nagar (Ward 124)",
  "Subrahmanyapura (Ward 203)",
  "Subramanya Nagar (Ward 59)",
  "Suddagunte Palya (Ward 178)",
  "Sunkadakatte (Ward 25)",
  "Sunkenahalli (Ward 162)",
  "T Dasarahalli (Ward 19)",
  "Thanisandra (Ward 7)",
  "Ullalu (Ward 29)",
  "Ulsoor (Ward 121)",
  "Uttarahalli (Ward 202)",
  "Vannarpet (Ward 169)",
  "Varthuru (Ward 104)",
  "Vasanthnagar (Ward 117)",
  "Vasanthpura (Ward 204)",
  "Vidyapeeta ward (Ward 199)",
  "Vidyaranyapura (Ward 13)",
  "Vijayanagar (Ward 145)",
  "Vijinapura (Ward 89)",
  "Vijnana Nagar (Ward 95)",
  "Vishveshwara Puram (Ward 163)",
  "Vishwanath Nagenahalli (Ward 64)",
  "Vrisabhavathi Nagar (Ward 53)",
  "White Field (Ward 103)",
  "Yediyur (Ward 188)",
  "Yelahanka Satellite Town (Ward 4)",
  "Yelchenahalli (Ward 205)",
  "Yeshwanthpura (Ward 35)"
];